### PR TITLE
Fix URI for x_pmt if it's the only parameter

### LINKED ISSUE #52: Wrong URI for x_pmt if it's the only parameter
When using the plugin with a Octopus NET it sometimes tries to do requests like `rtsp://[ip]/stream=1&x_pmt=2000` for encrypted channels. This request looks wrong because there should be a `?` instead of `&`. The Octopus NET answers with a status code 400.

Is there a check missing here?
https://github.com/rofafor/vdr-plugin-satip/blob/299296bbb1a7274e7c67abee64a6edc24bf965bc/tuner.c#L512

The check is done some lines above:
https://github.com/rofafor/vdr-plugin-satip/blob/299296bbb1a7274e7c67abee64a6edc24bf965bc/tuner.c#L499

### PR DESCRIPTION
**Pull request by mjanser**
Fixes #52

### CODE REVIEW

File: tuner.c [hunk 1]
```diff
@@ -486,17 +486,21 @@ bool cSatipTuner::UpdatePids(bool forceP)
      cString uri = cString::sprintf("%sstream=%d", *GetBaseUrl(*streamAddrM, streamPortM), streamIdM);
      bool useci = (SatipConfig.GetCIExtension() && currentServerM.HasCI());
      bool usedummy = currentServerM.IsQuirk(cSatipServer::eSatipQuirkPlayPids);
+     bool paramadded = false;
      if (forceP || usedummy) {
         if (pidsM.Size())
            uri = cString::sprintf("%s?pids=%s", *uri, *pidsM.ListPids());
```
Comment (rofafor) [inline tuner.c]: Could you add ```paramadded ? "&" : "?"``` logic also into this line? I know, it will be always ```false```, but any future modification will be adapted automatically afterwards.
Please, amend this also into the existing commit.

File: tuner.c [hunk 2]
```diff
@@ -509,7 +513,8 @@ bool cSatipTuner::UpdatePids(bool forceP)
            int pid = deviceM->GetPmtPid();
            if ((pid > 0) && (pid != pmtPidM)) {
               int slot = deviceM->GetCISlot();
-              uri = cString::sprintf("%s&x_pmt=%d", *uri, pid);
+              uri = cString::sprintf("%s%sx_pmt=%d", *uri, paramadded ? "&" : "?", pid);
+              paramadded = true;
```
Comment (rofafor) [inline tuner.c]: nit: this could be set a bit later - after the x_ci block.

File: tuner.c [hunk 3]
```diff
@@ -486,17 +486,21 @@ bool cSatipTuner::UpdatePids(bool forceP)
      cString uri = cString::sprintf("%sstream=%d", *GetBaseUrl(*streamAddrM, streamPortM), streamIdM);
      bool useci = (SatipConfig.GetCIExtension() && currentServerM.HasCI());
      bool usedummy = currentServerM.IsQuirk(cSatipServer::eSatipQuirkPlayPids);
+     bool paramadded = false;
      if (forceP || usedummy) {
         if (pidsM.Size())
-           uri = cString::sprintf("%s?pids=%s", *uri, *pidsM.ListPids());
+           uri = cString::sprintf("%s%spids=%s", *uri, paramadded ? "&" : "?", *pidsM.ListPids());
+           paramadded = true;
```
Comment (rofafor) [inline tuner.c]: Remember curly braces as the if-block isn't one-liner anymore.

File: tuner.c [hunk 4]
```diff
@@ -486,17 +486,21 @@ bool cSatipTuner::UpdatePids(bool forceP)
...
         if (usedummy && (pidsM.Size() == 1) && (pidsM[0] < 0x20))
```
Comment (rofafor) [inline tuner.c]: This could be intended one step more due to ```pidsM.Size() == 1``` check and ```paramadded = true;``` set afterwards.

File: tuner.c [hunk 5]
```diff
@@ -486,17 +486,21 @@ bool cSatipTuner::UpdatePids(bool forceP)
...
      else {
-        if (addPidsM.Size())
-           uri = cString::sprintf("%s?addpids=%s", *uri, *addPidsM.ListPids());
+        if (addPidsM.Size()) {
+           uri = cString::sprintf("%s%saddpids=%s", *uri, paramadded ? "&" : "?", *addPidsM.ListPids());
+           paramadded = true;
+           }
         if (delPidsM.Size())
-           uri = cString::sprintf("%s%sdelpids=%s", *uri, addPidsM.Size() ? "&" : "?", *delPidsM.ListPids());
+           uri = cString::sprintf("%s%sdelpids=%s", *uri, paramadded ? "&" : "?", *delPidsM.ListPids());
```
Comment (rofafor) [inline tuner.c]: Missing ```paramadded = true;```.
